# Generated by Django 4.0.1 on 2022-01-22 10:35

from django.db import migrations, models
import nepali_datetime_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerKoBaaki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_product', models.CharField(max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_price', models.FloatField(null=True)),
                ('miti', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
            ],
        ),
    ]
