# Generated by Django 4.0.1 on 2022-01-27 04:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerkobaaki_credited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkobaaki',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
