# Generated by Django 4.0.1 on 2022-01-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Total', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='count',
        ),
    ]
